name: SlimePlus
version: '1.0.0'
main: org.crzx.slimePlus.SlimePlus
description: Enhance your slime block mechanics with custom bounces and boosts!
api-version: '1.21'
load: STARTUP
authors: [ CRZX1337 ]
website: https://github.com/CRZX1337/
commands:
  slimeplus:
    description: Main command for SlimePlus
    usage: /slimeplus
    permission: slimeplus.admin
permissions:
  slimeplus.admin:
    description: Allows access to SlimePlus admin GUI
    default: op
