name: Bug Report
description: Create a report to help us improve SlimePlus
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SlimePlus Version
      description: What version of SlimePlus are you using? (e.g. 1.0.0)
    validations:
      required: true
  - type: dropdown
    id: server-platform
    attributes:
      label: Server Platform
      description: What server platform are you using?
      options:
        - CraftBukkit
        - Paper
        - Spigot
        - Purpur
        - Other
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      description: e.g. 1.21.1
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Please paste any relevant logs or upload screenshots.
      render: shell
