name: Feature Request
description: Suggest an idea for SlimePlus
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your idea
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      description: Explain how this feature would improve the plugin for everyone.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
